Adding a new test case
omeneses/automation_workshop pull request #2
Opened 2018-03-20 21:19 UTC by omeneses

go campi

2018-03-20 21:37 UTC, cecampino requested changes
Please address changes before merging.

2018-03-20 21:37 UTC, cecampino commented on src/main/java/pages/HomePageFS.java
> +
Remove empty lines

2018-03-20 21:37 UTC, cecampino commented on src/main/java/utils/CommonFuntions.java
>          }
Add default Statement

2018-03-20 21:37 UTC, cecampino commented on src/test/java/automation_workshop/GalleryTest.java
> +        createDriver(driverType.firefox);
Why did we change chrome?

2018-03-22 06:52 UTC, omeneses commented on src/test/java/automation_workshop/GalleryTest.java
> +        createDriver(driverType.firefox);
I just wanted use firefox  :)

2018-03-22 06:52 UTC, omeneses commented on src/main/java/utils/CommonFuntions.java
>          }
Done

2018-03-22 06:53 UTC, omeneses commented on src/main/java/pages/HomePageFS.java
> +
done

2018-04-12 19:26 UTC, cecampino approved these changes

2018-04-12 19:28 UTC, omeneses commented
Adding branch_6, removing some empty lines and adding Default statement to switch cases

2018-04-12 19:31 UTC, merged